apiVersion: batch/v1
kind: CronJob
metadata:
  name: run-umbrella-sync-script
spec:
  schedule: "0 * * * *"  # Runs at the top of every hour
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: umbrella-sync-script
            image: your-docker-repo/your-script:latest # set image
            imagePullPolicy: IfNotPresent
            command: ["./sync.sh"]
          restartPolicy: Never
