apiVersion: batch/v1
kind: CronJob
metadata:
  name: run-umbrella-git-sync
spec:
  schedule: "0 * * * *"  # Runs at the top of every hour
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: umbrella-git-sync
            image: {registry}/umbrella-git-sync:latest
            imagePullPolicy: IfNotPresent
            command: ["./sync.sh"]
          restartPolicy: Never
